### ISSUE TITLE
Multiple modules crash MkDocs

### ISSUE THREAD

**Issue by schmittner** [tlambert03/mkdocs-api-autonav#9]
MkDocs 1.6.1 crashes when your (awesome, btw!) plugin is used to create documentation for a project with multiple modules.

I've attached a minimal configuration.

```yaml
site_name: Test
plugins:
  - mkdocstrings
  - api-autonav:
      modules: ["src/package1", "src/package2"] # both with empty __init__.py
nav:
  - Home: index.md
```
